messages:

  # Minecraft to Telegram
  # Markdown supported

  general-message-to-telegram: "%s: %s"
  join-message: "`%s joined the game.`"
  quit-message: "`%s left the game.`"
  death-message: "`%s`"

  # Telegram to Minecraft
  # Minecraft color codes supported

  # Used for regular text messages
  general-message-to-mc: "&c[Telegram]&r %s: %s"
  # Used for special messages without a caption
  special-message-without-caption: "&c[Telegram]&r %s &7%s&r"
  # Used for special messages which the sender has added a caption to. Also used for polls and pinned messages.
  special-message-with-caption: "&c[Telegram]&r %s &7%s: &r%s"
  # Leave blank to disable forwarding individual message types
  photo: "sent an image"
  video: "sent a video"
  animation: "posted a GIF"
  audio: "sent an audio file"
  document: "sent a file"
  sticker: "posted a sticker"
  voice: "sent a voice message"
  videonote: "sent a video message"
  poll: "started a poll"
  location: "sent a location"
  pinned: "pinned a message"

  # Setup

  # In Telegram
  need-to-link: "Sorry, please link your account with */linktelegram ingame* to use the chat!"
  can-see-but-not-chat: "You can see the chat but you can't chat at the moment. Type */linktelegram ingame* to chat!"
  success-linked: "Success! Linked %s"
  setup-msg: "Congratulations, your bot is working! Have fun with this Plugin. Feel free to donate via *PayPal* to keep this project up to date! [PayPal Donation URL](http://donate.spaceio.xyz/)"
  # In Minecraft
  no-permissions: "&cYou don't have permissions to use this!"
  cant-link-console: "&cSorry, but you can't link the console currently."
  need-to-add-bot-first: "&cPlease add a bot to your server first! /telegram"
  get-token: "&aAdd %s to Telegram and send this message to %s: \n%s"

enable-joinquitmessages: true
enable-deathmessages: true
enable-chatmessages: true
# Suppress notification sounds when sending these types of messages to Telegram. See https://telegram.org/blog/silent-messages-slow-mode
silent-joinquitmessages: false
silent-deathmessages: false
silent-chatmessages: false

# If a player joins within this number of minutes after leaving, the bot will delete the quit message instead of sending a join message.
# This helps keep the Telegram chat clean by reducing spam due to players with connection issues or players leaving the server to skip the night.
# Set to 0 to disable this feature.
delete-quitmessages-within: 1

# Allows group chat users to use the chat bridge without having linked their accounts.
# Note that this will allow banned players to still use the chat if they have an unlinked Telegram account.
# Users will still be able to link their accounts to have their Minecraft username displayed on messages forwarded to Minecraft.
no-link-required: false

# Enable to automatically update a group chat's description to include the current list of online players.
enable-group-description: false
# Configure the chat description below. Please note that Telegram unfortunately doesn't support Markdown in chat descriptions, and that chat descriptions cannot be longer than 255 characters.
group-description:
  # Static text that should always be in the description. Put %s where you want the generated part to be inserted.
  base: "Welcome to our server's group chat!\n\n%s"
  # When at least one player is online, display the total number here.
  num-players: "%s player(s) online"
  # Repeated on a new line for every online player
  player: "- %s"
  # Replaces the player list when nobody is online
  nobody-online: "There are no players currently online."
  # Used when the server goes offline or the plugin gets disabled for another reason.
  # Might not be sent when the server doesn't stop gracefully (crash, power outage, etc.)
  offline: "The server is offline."
